<?php

/**
 * This is the model base class for the table "upnpmedia".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Upnpmedia".
 *
 * Columns in table "upnpmedia" available as properties of the model,
 * and there are no model relations.
 *
 * @property string $intid
 * @property string $class
 * @property string $itemtype
 * @property string $parentid
 * @property string $itemproperties
 * @property string $filepath
 * @property string $title
 * @property string $filename
 * @property string $coverart
 *
 */
abstract class BaseUpnpmedia extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'upnpmedia';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Upnpmedia|Upnpmedias', $n);
	}

	public static function representingColumn() {
		return 'class';
	}

	public function rules() {
		return array(
			array('intid, parentid', 'length', 'max'=>10),
			array('class', 'length', 'max'=>64),
			array('itemtype', 'length', 'max'=>128),
			array('itemproperties, title', 'length', 'max'=>255),
			array('filepath, filename, coverart', 'length', 'max'=>512),
			array('intid, class, itemtype, parentid, itemproperties, filepath, title, filename, coverart', 'default', 'setOnEmpty' => true, 'value' => null),
			array('intid, class, itemtype, parentid, itemproperties, filepath, title, filename, coverart', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'intid' => Yii::t('app', 'Intid'),
			'class' => Yii::t('app', 'Class'),
			'itemtype' => Yii::t('app', 'Itemtype'),
			'parentid' => Yii::t('app', 'Parentid'),
			'itemproperties' => Yii::t('app', 'Itemproperties'),
			'filepath' => Yii::t('app', 'Filepath'),
			'title' => Yii::t('app', 'Title'),
			'filename' => Yii::t('app', 'Filename'),
			'coverart' => Yii::t('app', 'Coverart'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('intid', $this->intid, true);
		$criteria->compare('class', $this->class, true);
		$criteria->compare('itemtype', $this->itemtype, true);
		$criteria->compare('parentid', $this->parentid, true);
		$criteria->compare('itemproperties', $this->itemproperties, true);
		$criteria->compare('filepath', $this->filepath, true);
		$criteria->compare('title', $this->title, true);
		$criteria->compare('filename', $this->filename, true);
		$criteria->compare('coverart', $this->coverart, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}