<?php

/**
 * This is the model base class for the table "channelscan_dtv_multiplex".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "ChannelscanDtvMultiplex".
 *
 * Columns in table "channelscan_dtv_multiplex" available as properties of the model,
 * and there are no model relations.
 *
 * @property string $transportid
 * @property string $scanid
 * @property integer $mplexid
 * @property string $frequency
 * @property string $inversion
 * @property string $symbolrate
 * @property string $fec
 * @property string $polarity
 * @property string $hp_code_rate
 * @property string $mod_sys
 * @property string $rolloff
 * @property string $lp_code_rate
 * @property string $modulation
 * @property string $transmission_mode
 * @property string $guard_interval
 * @property string $hierarchy
 * @property string $bandwidth
 * @property string $sistandard
 * @property integer $tuner_type
 * @property string $default_authority
 *
 */
abstract class BaseChannelscanDtvMultiplex extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'channelscan_dtv_multiplex';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'ChannelscanDtvMultiplex|ChannelscanDtvMultiplexes', $n);
	}

	public static function representingColumn() {
		return 'inversion';
	}

	public function rules() {
		return array(
			array('scanid, mplexid, frequency, sistandard, tuner_type', 'required'),
			array('mplexid, tuner_type', 'numerical', 'integerOnly'=>true),
			array('scanid', 'length', 'max'=>3),
			array('frequency, symbolrate', 'length', 'max'=>12),
			array('inversion, polarity, transmission_mode, bandwidth', 'length', 'max'=>1),
			array('fec, hp_code_rate, mod_sys, lp_code_rate, modulation, guard_interval, hierarchy, sistandard', 'length', 'max'=>10),
			array('rolloff', 'length', 'max'=>4),
			array('default_authority', 'length', 'max'=>32),
			array('inversion, symbolrate, fec, polarity, hp_code_rate, mod_sys, rolloff, lp_code_rate, modulation, transmission_mode, guard_interval, hierarchy, bandwidth, default_authority', 'default', 'setOnEmpty' => true, 'value' => null),
			array('transportid, scanid, mplexid, frequency, inversion, symbolrate, fec, polarity, hp_code_rate, mod_sys, rolloff, lp_code_rate, modulation, transmission_mode, guard_interval, hierarchy, bandwidth, sistandard, tuner_type, default_authority', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'transportid' => Yii::t('app', 'Transportid'),
			'scanid' => Yii::t('app', 'Scanid'),
			'mplexid' => Yii::t('app', 'Mplexid'),
			'frequency' => Yii::t('app', 'Frequency'),
			'inversion' => Yii::t('app', 'Inversion'),
			'symbolrate' => Yii::t('app', 'Symbolrate'),
			'fec' => Yii::t('app', 'Fec'),
			'polarity' => Yii::t('app', 'Polarity'),
			'hp_code_rate' => Yii::t('app', 'Hp Code Rate'),
			'mod_sys' => Yii::t('app', 'Mod Sys'),
			'rolloff' => Yii::t('app', 'Rolloff'),
			'lp_code_rate' => Yii::t('app', 'Lp Code Rate'),
			'modulation' => Yii::t('app', 'Modulation'),
			'transmission_mode' => Yii::t('app', 'Transmission Mode'),
			'guard_interval' => Yii::t('app', 'Guard Interval'),
			'hierarchy' => Yii::t('app', 'Hierarchy'),
			'bandwidth' => Yii::t('app', 'Bandwidth'),
			'sistandard' => Yii::t('app', 'Sistandard'),
			'tuner_type' => Yii::t('app', 'Tuner Type'),
			'default_authority' => Yii::t('app', 'Default Authority'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('transportid', $this->transportid, true);
		$criteria->compare('scanid', $this->scanid, true);
		$criteria->compare('mplexid', $this->mplexid);
		$criteria->compare('frequency', $this->frequency, true);
		$criteria->compare('inversion', $this->inversion, true);
		$criteria->compare('symbolrate', $this->symbolrate, true);
		$criteria->compare('fec', $this->fec, true);
		$criteria->compare('polarity', $this->polarity, true);
		$criteria->compare('hp_code_rate', $this->hp_code_rate, true);
		$criteria->compare('mod_sys', $this->mod_sys, true);
		$criteria->compare('rolloff', $this->rolloff, true);
		$criteria->compare('lp_code_rate', $this->lp_code_rate, true);
		$criteria->compare('modulation', $this->modulation, true);
		$criteria->compare('transmission_mode', $this->transmission_mode, true);
		$criteria->compare('guard_interval', $this->guard_interval, true);
		$criteria->compare('hierarchy', $this->hierarchy, true);
		$criteria->compare('bandwidth', $this->bandwidth, true);
		$criteria->compare('sistandard', $this->sistandard, true);
		$criteria->compare('tuner_type', $this->tuner_type);
		$criteria->compare('default_authority', $this->default_authority, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}