<?php

/**
 * This is the model base class for the table "tbl_migration".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "TblMigration".
 *
 * Columns in table "tbl_migration" available as properties of the model,
 * and there are no model relations.
 *
 * @property string $version
 * @property integer $apply_time
 *
 */
abstract class BaseTblMigration extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'tbl_migration';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'TblMigration|TblMigrations', $n);
	}

	public static function representingColumn() {
		return 'version';
	}

	public function rules() {
		return array(
			array('version', 'required'),
			array('apply_time', 'numerical', 'integerOnly'=>true),
			array('version', 'length', 'max'=>255),
			array('apply_time', 'default', 'setOnEmpty' => true, 'value' => null),
			array('version, apply_time', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'version' => Yii::t('app', 'Version'),
			'apply_time' => Yii::t('app', 'Apply Time'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('version', $this->version, true);
		$criteria->compare('apply_time', $this->apply_time);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}