<?php

/**
 * This is the model base class for the table "internetcontentarticles".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Internetcontentarticles".
 *
 * Columns in table "internetcontentarticles" available as properties of the model,
 * and there are no model relations.
 *
 * @property string $feedtitle
 * @property string $path
 * @property string $paththumb
 * @property string $title
 * @property string $subtitle
 * @property integer $season
 * @property integer $episode
 * @property string $description
 * @property string $url
 * @property integer $type
 * @property string $thumbnail
 * @property string $mediaURL
 * @property string $author
 * @property string $date
 * @property integer $time
 * @property string $rating
 * @property string $filesize
 * @property string $player
 * @property string $playerargs
 * @property string $download
 * @property string $downloadargs
 * @property integer $width
 * @property integer $height
 * @property string $language
 * @property integer $podcast
 * @property integer $downloadable
 * @property integer $customhtml
 * @property string $countries
 *
 */
abstract class BaseInternetcontentarticles extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'internetcontentarticles';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Internetcontentarticles|Internetcontentarticles', $n);
	}

	public static function representingColumn() {
		return 'feedtitle';
	}

	public function rules() {
		return array(
			array('feedtitle, path, paththumb, title, subtitle, description, url, type, thumbnail, mediaURL, author, time, rating, filesize, player, playerargs, download, downloadargs, width, height, language, podcast, downloadable, customhtml, countries', 'required'),
			array('season, episode, type, time, width, height, podcast, downloadable, customhtml', 'numerical', 'integerOnly'=>true),
			array('feedtitle, title, subtitle, author, rating, player, download, countries', 'length', 'max'=>255),
			array('filesize', 'length', 'max'=>20),
			array('language', 'length', 'max'=>128),
			array('date', 'safe'),
			array('season, episode, date', 'default', 'setOnEmpty' => true, 'value' => null),
			array('feedtitle, path, paththumb, title, subtitle, season, episode, description, url, type, thumbnail, mediaURL, author, date, time, rating, filesize, player, playerargs, download, downloadargs, width, height, language, podcast, downloadable, customhtml, countries', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'feedtitle' => Yii::t('app', 'Feedtitle'),
			'path' => Yii::t('app', 'Path'),
			'paththumb' => Yii::t('app', 'Paththumb'),
			'title' => Yii::t('app', 'Title'),
			'subtitle' => Yii::t('app', 'Subtitle'),
			'season' => Yii::t('app', 'Season'),
			'episode' => Yii::t('app', 'Episode'),
			'description' => Yii::t('app', 'Description'),
			'url' => Yii::t('app', 'Url'),
			'type' => Yii::t('app', 'Type'),
			'thumbnail' => Yii::t('app', 'Thumbnail'),
			'mediaURL' => Yii::t('app', 'Media Url'),
			'author' => Yii::t('app', 'Author'),
			'date' => Yii::t('app', 'Date'),
			'time' => Yii::t('app', 'Time'),
			'rating' => Yii::t('app', 'Rating'),
			'filesize' => Yii::t('app', 'Filesize'),
			'player' => Yii::t('app', 'Player'),
			'playerargs' => Yii::t('app', 'Playerargs'),
			'download' => Yii::t('app', 'Download'),
			'downloadargs' => Yii::t('app', 'Downloadargs'),
			'width' => Yii::t('app', 'Width'),
			'height' => Yii::t('app', 'Height'),
			'language' => Yii::t('app', 'Language'),
			'podcast' => Yii::t('app', 'Podcast'),
			'downloadable' => Yii::t('app', 'Downloadable'),
			'customhtml' => Yii::t('app', 'Customhtml'),
			'countries' => Yii::t('app', 'Countries'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('feedtitle', $this->feedtitle, true);
		$criteria->compare('path', $this->path, true);
		$criteria->compare('paththumb', $this->paththumb, true);
		$criteria->compare('title', $this->title, true);
		$criteria->compare('subtitle', $this->subtitle, true);
		$criteria->compare('season', $this->season);
		$criteria->compare('episode', $this->episode);
		$criteria->compare('description', $this->description, true);
		$criteria->compare('url', $this->url, true);
		$criteria->compare('type', $this->type);
		$criteria->compare('thumbnail', $this->thumbnail, true);
		$criteria->compare('mediaURL', $this->mediaURL, true);
		$criteria->compare('author', $this->author, true);
		$criteria->compare('date', $this->date, true);
		$criteria->compare('time', $this->time);
		$criteria->compare('rating', $this->rating, true);
		$criteria->compare('filesize', $this->filesize, true);
		$criteria->compare('player', $this->player, true);
		$criteria->compare('playerargs', $this->playerargs, true);
		$criteria->compare('download', $this->download, true);
		$criteria->compare('downloadargs', $this->downloadargs, true);
		$criteria->compare('width', $this->width);
		$criteria->compare('height', $this->height);
		$criteria->compare('language', $this->language, true);
		$criteria->compare('podcast', $this->podcast);
		$criteria->compare('downloadable', $this->downloadable);
		$criteria->compare('customhtml', $this->customhtml);
		$criteria->compare('countries', $this->countries, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}