<?php

/**
 * This is the model base class for the table "recordedmarkup".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Recordedmarkup".
 *
 * Columns in table "recordedmarkup" available as properties of the model,
 * and there are no model relations.
 *
 * @property string $chanid
 * @property string $starttime
 * @property integer $mark
 * @property integer $type
 * @property string $data
 *
 */
abstract class BaseRecordedmarkup extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'recordedmarkup';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Recordedmarkup|Recordedmarkups', $n);
	}

	public static function representingColumn() {
		return 'starttime';
	}

	public function rules() {
		return array(
			array('mark, type', 'numerical', 'integerOnly'=>true),
			array('chanid', 'length', 'max'=>10),
			array('data', 'length', 'max'=>11),
			array('chanid, starttime, mark, type, data', 'default', 'setOnEmpty' => true, 'value' => null),
			array('chanid, starttime, mark, type, data', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'chanid' => Yii::t('app', 'Chanid'),
			'starttime' => Yii::t('app', 'Starttime'),
			'mark' => Yii::t('app', 'Mark'),
			'type' => Yii::t('app', 'Type'),
			'data' => Yii::t('app', 'Data'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('chanid', $this->chanid, true);
		$criteria->compare('starttime', $this->starttime, true);
		$criteria->compare('mark', $this->mark);
		$criteria->compare('type', $this->type);
		$criteria->compare('data', $this->data, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}