<?php

/**
 * This is the model base class for the table "videopathinfo".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Videopathinfo".
 *
 * Columns in table "videopathinfo" available as properties of the model,
 * and there are no model relations.
 *
 * @property string $intid
 * @property string $path
 * @property string $contenttype
 * @property integer $collectionref
 * @property integer $recurse
 *
 */
abstract class BaseVideopathinfo extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'videopathinfo';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Videopathinfo|Videopathinfos', $n);
	}

	public static function representingColumn() {
		return 'contenttype';
	}

	public function rules() {
		return array(
			array('collectionref, recurse', 'numerical', 'integerOnly'=>true),
			array('path, contenttype', 'safe'),
			array('path, contenttype, collectionref, recurse', 'default', 'setOnEmpty' => true, 'value' => null),
			array('intid, path, contenttype, collectionref, recurse', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'intid' => Yii::t('app', 'Intid'),
			'path' => Yii::t('app', 'Path'),
			'contenttype' => Yii::t('app', 'Contenttype'),
			'collectionref' => Yii::t('app', 'Collectionref'),
			'recurse' => Yii::t('app', 'Recurse'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('intid', $this->intid, true);
		$criteria->compare('path', $this->path, true);
		$criteria->compare('contenttype', $this->contenttype, true);
		$criteria->compare('collectionref', $this->collectionref);
		$criteria->compare('recurse', $this->recurse);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}