<?php

/**
 * This is the model base class for the table "netflix".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Netflix".
 *
 * Columns in table "netflix" available as properties of the model,
 * and there are no model relations.
 *
 * @property string $name
 * @property string $category
 * @property string $url
 * @property string $ico
 * @property string $updated
 * @property string $is_queue
 * @property string $queue
 *
 */
abstract class BaseNetflix extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'netflix';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Netflix|Netflixes', $n);
	}

	public static function representingColumn() {
		return 'category';
	}

	public function rules() {
		return array(
			array('name, category, url', 'required'),
			array('name', 'length', 'max'=>100),
			array('category, url, ico', 'length', 'max'=>255),
			array('updated, is_queue', 'length', 'max'=>10),
			array('queue', 'length', 'max'=>32),
			array('ico, updated, is_queue, queue', 'default', 'setOnEmpty' => true, 'value' => null),
			array('name, category, url, ico, updated, is_queue, queue', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'name' => Yii::t('app', 'Name'),
			'category' => Yii::t('app', 'Category'),
			'url' => Yii::t('app', 'Url'),
			'ico' => Yii::t('app', 'Ico'),
			'updated' => Yii::t('app', 'Updated'),
			'is_queue' => Yii::t('app', 'Is Queue'),
			'queue' => Yii::t('app', 'Queue'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('name', $this->name, true);
		$criteria->compare('category', $this->category, true);
		$criteria->compare('url', $this->url, true);
		$criteria->compare('ico', $this->ico, true);
		$criteria->compare('updated', $this->updated, true);
		$criteria->compare('is_queue', $this->is_queue, true);
		$criteria->compare('queue', $this->queue, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}