<?php

/**
 * This is the model base class for the table "music_artists".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "MusicArtists".
 *
 * Columns in table "music_artists" available as properties of the model,
 * and there are no model relations.
 *
 * @property string $artist_id
 * @property string $artist_name
 *
 */
abstract class BaseMusicArtists extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'music_artists';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'MusicArtists|MusicArtists', $n);
	}

	public static function representingColumn() {
		return 'artist_name';
	}

	public function rules() {
		return array(
			array('artist_name', 'length', 'max'=>255),
			array('artist_name', 'default', 'setOnEmpty' => true, 'value' => null),
			array('artist_id, artist_name', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'artist_id' => Yii::t('app', 'Artist'),
			'artist_name' => Yii::t('app', 'Artist Name'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('artist_id', $this->artist_id, true);
		$criteria->compare('artist_name', $this->artist_name, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}