<?php

/**
 * This is the model base class for the table "diseqc_config".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "DiseqcConfig".
 *
 * Columns in table "diseqc_config" available as properties of the model,
 * and there are no model relations.
 *
 * @property string $cardinputid
 * @property string $diseqcid
 * @property string $value
 *
 */
abstract class BaseDiseqcConfig extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'diseqc_config';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'DiseqcConfig|DiseqcConfigs', $n);
	}

	public static function representingColumn() {
		return 'value';
	}

	public function rules() {
		return array(
			array('cardinputid, diseqcid', 'required'),
			array('cardinputid, diseqcid', 'length', 'max'=>10),
			array('value', 'length', 'max'=>16),
			array('value', 'default', 'setOnEmpty' => true, 'value' => null),
			array('cardinputid, diseqcid, value', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'cardinputid' => Yii::t('app', 'Cardinputid'),
			'diseqcid' => Yii::t('app', 'Diseqcid'),
			'value' => Yii::t('app', 'Value'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('cardinputid', $this->cardinputid, true);
		$criteria->compare('diseqcid', $this->diseqcid, true);
		$criteria->compare('value', $this->value, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}