<?php

/**
 * This is the model base class for the table "housekeeping".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Housekeeping".
 *
 * Columns in table "housekeeping" available as properties of the model,
 * and there are no model relations.
 *
 * @property string $tag
 * @property string $lastrun
 *
 */
abstract class BaseHousekeeping extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'housekeeping';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Housekeeping|Housekeepings', $n);
	}

	public static function representingColumn() {
		return 'tag';
	}

	public function rules() {
		return array(
			array('tag', 'length', 'max'=>64),
			array('lastrun', 'safe'),
			array('tag, lastrun', 'default', 'setOnEmpty' => true, 'value' => null),
			array('tag, lastrun', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'tag' => Yii::t('app', 'Tag'),
			'lastrun' => Yii::t('app', 'Lastrun'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('tag', $this->tag, true);
		$criteria->compare('lastrun', $this->lastrun, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}