<?php

/**
 * This is the model base class for the table "keyword".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Keyword".
 *
 * Columns in table "keyword" available as properties of the model,
 * and there are no model relations.
 *
 * @property string $phrase
 * @property string $searchtype
 *
 */
abstract class BaseKeyword extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'keyword';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Keyword|Keywords', $n);
	}

	public static function representingColumn() {
		return 'phrase';
	}

	public function rules() {
		return array(
			array('phrase', 'length', 'max'=>128),
			array('searchtype', 'length', 'max'=>10),
			array('phrase, searchtype', 'default', 'setOnEmpty' => true, 'value' => null),
			array('phrase, searchtype', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'phrase' => Yii::t('app', 'Phrase'),
			'searchtype' => Yii::t('app', 'Searchtype'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('phrase', $this->phrase, true);
		$criteria->compare('searchtype', $this->searchtype, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}