<?php

/**
 * This is the model base class for the table "jobqueue".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Jobqueue".
 *
 * Columns in table "jobqueue" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property integer $chanid
 * @property string $starttime
 * @property string $inserttime
 * @property integer $type
 * @property integer $cmds
 * @property integer $flags
 * @property integer $status
 * @property string $statustime
 * @property string $hostname
 * @property string $args
 * @property string $comment
 * @property string $schedruntime
 *
 */
abstract class BaseJobqueue extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'jobqueue';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Jobqueue|Jobqueues', $n);
	}

	public static function representingColumn() {
		return 'starttime';
	}

	public function rules() {
		return array(
			array('statustime, args', 'required'),
			array('chanid, type, cmds, flags, status', 'numerical', 'integerOnly'=>true),
			array('hostname', 'length', 'max'=>64),
			array('comment', 'length', 'max'=>128),
			array('starttime, inserttime, schedruntime', 'safe'),
			array('chanid, starttime, inserttime, type, cmds, flags, status, hostname, comment, schedruntime', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, chanid, starttime, inserttime, type, cmds, flags, status, statustime, hostname, args, comment, schedruntime', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'chanid' => Yii::t('app', 'Chanid'),
			'starttime' => Yii::t('app', 'Starttime'),
			'inserttime' => Yii::t('app', 'Inserttime'),
			'type' => Yii::t('app', 'Type'),
			'cmds' => Yii::t('app', 'Cmds'),
			'flags' => Yii::t('app', 'Flags'),
			'status' => Yii::t('app', 'Status'),
			'statustime' => Yii::t('app', 'Statustime'),
			'hostname' => Yii::t('app', 'Hostname'),
			'args' => Yii::t('app', 'Args'),
			'comment' => Yii::t('app', 'Comment'),
			'schedruntime' => Yii::t('app', 'Schedruntime'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('chanid', $this->chanid);
		$criteria->compare('starttime', $this->starttime, true);
		$criteria->compare('inserttime', $this->inserttime, true);
		$criteria->compare('type', $this->type);
		$criteria->compare('cmds', $this->cmds);
		$criteria->compare('flags', $this->flags);
		$criteria->compare('status', $this->status);
		$criteria->compare('statustime', $this->statustime, true);
		$criteria->compare('hostname', $this->hostname, true);
		$criteria->compare('args', $this->args, true);
		$criteria->compare('comment', $this->comment, true);
		$criteria->compare('schedruntime', $this->schedruntime, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}