<?php

/**
 * This is the model base class for the table "movies_theaters".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "MoviesTheaters".
 *
 * Columns in table "movies_theaters" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property string $theatername
 * @property string $theateraddress
 *
 */
abstract class BaseMoviesTheaters extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'movies_theaters';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'MoviesTheaters|MoviesTheaters', $n);
	}

	public static function representingColumn() {
		return 'theatername';
	}

	public function rules() {
		return array(
			array('theatername, theateraddress', 'length', 'max'=>100),
			array('theatername, theateraddress', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, theatername, theateraddress', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'theatername' => Yii::t('app', 'Theatername'),
			'theateraddress' => Yii::t('app', 'Theateraddress'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('theatername', $this->theatername, true);
		$criteria->compare('theateraddress', $this->theateraddress, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}