<?php

/**
 * This is the model base class for the table "oldprogram".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Oldprogram".
 *
 * Columns in table "oldprogram" available as properties of the model,
 * and there are no model relations.
 *
 * @property string $oldtitle
 * @property string $airdate
 *
 */
abstract class BaseOldprogram extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'oldprogram';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Oldprogram|Oldprograms', $n);
	}

	public static function representingColumn() {
		return 'airdate';
	}

	public function rules() {
		return array(
			array('oldtitle', 'length', 'max'=>128),
			array('airdate', 'safe'),
			array('oldtitle, airdate', 'default', 'setOnEmpty' => true, 'value' => null),
			array('oldtitle, airdate', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'oldtitle' => Yii::t('app', 'Oldtitle'),
			'airdate' => Yii::t('app', 'Airdate'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('oldtitle', $this->oldtitle, true);
		$criteria->compare('airdate', $this->airdate, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}