<?php

/**
 * This is the model base class for the table "programgenres".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Programgenres".
 *
 * Columns in table "programgenres" available as properties of the model,
 * and there are no model relations.
 *
 * @property string $chanid
 * @property string $starttime
 * @property string $relevance
 * @property string $genre
 *
 */
abstract class BaseProgramgenres extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'programgenres';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Programgenres|Programgenres', $n);
	}

	public static function representingColumn() {
		return 'starttime';
	}

	public function rules() {
		return array(
			array('chanid', 'length', 'max'=>10),
			array('relevance', 'length', 'max'=>1),
			array('genre', 'length', 'max'=>30),
			array('chanid, starttime, relevance, genre', 'default', 'setOnEmpty' => true, 'value' => null),
			array('chanid, starttime, relevance, genre', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'chanid' => Yii::t('app', 'Chanid'),
			'starttime' => Yii::t('app', 'Starttime'),
			'relevance' => Yii::t('app', 'Relevance'),
			'genre' => Yii::t('app', 'Genre'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('chanid', $this->chanid, true);
		$criteria->compare('starttime', $this->starttime, true);
		$criteria->compare('relevance', $this->relevance, true);
		$criteria->compare('genre', $this->genre, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}