<?php

/**
 * This is the model base class for the table "videocategory".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Videocategory".
 *
 * Columns in table "videocategory" available as properties of the model,
 * and there are no model relations.
 *
 * @property string $intid
 * @property string $category
 *
 */
abstract class BaseVideocategory extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'videocategory';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Videocategory|Videocategories', $n);
	}

	public static function representingColumn() {
		return 'category';
	}

	public function rules() {
		return array(
			array('category', 'required'),
			array('category', 'length', 'max'=>128),
			array('intid, category', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'intid' => Yii::t('app', 'Intid'),
			'category' => Yii::t('app', 'Category'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('intid', $this->intid, true);
		$criteria->compare('category', $this->category, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}