<?php

/**
 * This is the model base class for the table "videometadatacountry".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Videometadatacountry".
 *
 * Columns in table "videometadatacountry" available as properties of the model,
 * and there are no model relations.
 *
 * @property string $idvideo
 * @property string $idcountry
 *
 */
abstract class BaseVideometadatacountry extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'videometadatacountry';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Videometadatacountry|Videometadatacountries', $n);
	}

	public static function representingColumn() {
		return array(
			'idvideo',
			'idcountry',
		);
	}

	public function rules() {
		return array(
			array('idvideo, idcountry', 'required'),
			array('idvideo, idcountry', 'length', 'max'=>10),
			array('idvideo, idcountry', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'idvideo' => Yii::t('app', 'Idvideo'),
			'idcountry' => Yii::t('app', 'Idcountry'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('idvideo', $this->idvideo, true);
		$criteria->compare('idcountry', $this->idcountry, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}