<?php

/**
 * This is the model base class for the table "videocountry".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Videocountry".
 *
 * Columns in table "videocountry" available as properties of the model,
 * and there are no model relations.
 *
 * @property string $intid
 * @property string $country
 *
 */
abstract class BaseVideocountry extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'videocountry';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Videocountry|Videocountries', $n);
	}

	public static function representingColumn() {
		return 'country';
	}

	public function rules() {
		return array(
			array('country', 'required'),
			array('country', 'length', 'max'=>128),
			array('intid, country', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'intid' => Yii::t('app', 'Intid'),
			'country' => Yii::t('app', 'Country'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('intid', $this->intid, true);
		$criteria->compare('country', $this->country, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}