<?php

/**
 * This is the model base class for the table "displayprofiles".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Displayprofiles".
 *
 * Columns in table "displayprofiles" available as properties of the model,
 * and there are no model relations.
 *
 * @property string $profilegroupid
 * @property string $profileid
 * @property string $value
 * @property string $data
 *
 */
abstract class BaseDisplayprofiles extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'displayprofiles';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Displayprofiles|Displayprofiles', $n);
	}

	public static function representingColumn() {
		return 'value';
	}

	public function rules() {
		return array(
			array('profilegroupid, value', 'required'),
			array('profilegroupid', 'length', 'max'=>10),
			array('value', 'length', 'max'=>128),
			array('data', 'length', 'max'=>255),
			array('data', 'default', 'setOnEmpty' => true, 'value' => null),
			array('profilegroupid, profileid, value, data', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'profilegroupid' => Yii::t('app', 'Profilegroupid'),
			'profileid' => Yii::t('app', 'Profileid'),
			'value' => Yii::t('app', 'Value'),
			'data' => Yii::t('app', 'Data'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('profilegroupid', $this->profilegroupid, true);
		$criteria->compare('profileid', $this->profileid, true);
		$criteria->compare('value', $this->value, true);
		$criteria->compare('data', $this->data, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}