<?php

/**
 * This is the model base class for the table "phonedirectory".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Phonedirectory".
 *
 * Columns in table "phonedirectory" available as properties of the model,
 * and there are no model relations.
 *
 * @property string $intid
 * @property string $nickname
 * @property string $firstname
 * @property string $surname
 * @property string $url
 * @property string $directory
 * @property string $photofile
 * @property string $speeddial
 * @property string $onhomelan
 *
 */
abstract class BasePhonedirectory extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'phonedirectory';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Phonedirectory|Phonedirectories', $n);
	}

	public static function representingColumn() {
		return 'nickname';
	}

	public function rules() {
		return array(
			array('nickname, url, directory, speeddial', 'required'),
			array('speeddial, onhomelan', 'length', 'max'=>10),
			array('firstname, surname, photofile', 'safe'),
			array('firstname, surname, photofile, onhomelan', 'default', 'setOnEmpty' => true, 'value' => null),
			array('intid, nickname, firstname, surname, url, directory, photofile, speeddial, onhomelan', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'intid' => Yii::t('app', 'Intid'),
			'nickname' => Yii::t('app', 'Nickname'),
			'firstname' => Yii::t('app', 'Firstname'),
			'surname' => Yii::t('app', 'Surname'),
			'url' => Yii::t('app', 'Url'),
			'directory' => Yii::t('app', 'Directory'),
			'photofile' => Yii::t('app', 'Photofile'),
			'speeddial' => Yii::t('app', 'Speeddial'),
			'onhomelan' => Yii::t('app', 'Onhomelan'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('intid', $this->intid, true);
		$criteria->compare('nickname', $this->nickname, true);
		$criteria->compare('firstname', $this->firstname, true);
		$criteria->compare('surname', $this->surname, true);
		$criteria->compare('url', $this->url, true);
		$criteria->compare('directory', $this->directory, true);
		$criteria->compare('photofile', $this->photofile, true);
		$criteria->compare('speeddial', $this->speeddial, true);
		$criteria->compare('onhomelan', $this->onhomelan, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}