<?php

/**
 * This is the model base class for the table "codecparams".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Codecparams".
 *
 * Columns in table "codecparams" available as properties of the model,
 * and there are no model relations.
 *
 * @property string $profile
 * @property string $name
 * @property string $value
 *
 */
abstract class BaseCodecparams extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'codecparams';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Codecparams|Codecparams', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array('profile', 'length', 'max'=>10),
			array('name, value', 'length', 'max'=>128),
			array('profile, name, value', 'default', 'setOnEmpty' => true, 'value' => null),
			array('profile, name, value', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'profile' => Yii::t('app', 'Profile'),
			'name' => Yii::t('app', 'Name'),
			'value' => Yii::t('app', 'Value'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('profile', $this->profile, true);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('value', $this->value, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}