<?php

/**
 * This is the model base class for the table "recordingprofiles".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Recordingprofiles".
 *
 * Columns in table "recordingprofiles" available as properties of the model,
 * and there are no model relations.
 *
 * @property string $id
 * @property string $name
 * @property string $videocodec
 * @property string $audiocodec
 * @property string $profilegroup
 *
 */
abstract class BaseRecordingprofiles extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'recordingprofiles';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Recordingprofiles|Recordingprofiles', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array('name, videocodec, audiocodec', 'length', 'max'=>128),
			array('profilegroup', 'length', 'max'=>10),
			array('name, videocodec, audiocodec, profilegroup', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, name, videocodec, audiocodec, profilegroup', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'name' => Yii::t('app', 'Name'),
			'videocodec' => Yii::t('app', 'Videocodec'),
			'audiocodec' => Yii::t('app', 'Audiocodec'),
			'profilegroup' => Yii::t('app', 'Profilegroup'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('videocodec', $this->videocodec, true);
		$criteria->compare('audiocodec', $this->audiocodec, true);
		$criteria->compare('profilegroup', $this->profilegroup, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}