<?php

/**
 * This is the model base class for the table "gallerymetadata".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Gallerymetadata".
 *
 * Columns in table "gallerymetadata" available as properties of the model,
 * and there are no model relations.
 *
 * @property string $image
 * @property integer $angle
 *
 */
abstract class BaseGallerymetadata extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'gallerymetadata';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Gallerymetadata|Gallerymetadatas', $n);
	}

	public static function representingColumn() {
		return 'image';
	}

	public function rules() {
		return array(
			array('image, angle', 'required'),
			array('angle', 'numerical', 'integerOnly'=>true),
			array('image', 'length', 'max'=>255),
			array('image, angle', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'image' => Yii::t('app', 'Image'),
			'angle' => Yii::t('app', 'Angle'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('image', $this->image, true);
		$criteria->compare('angle', $this->angle);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}