<?php

/**
 * This is the model base class for the table "videogenre".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Videogenre".
 *
 * Columns in table "videogenre" available as properties of the model,
 * and there are no model relations.
 *
 * @property string $intid
 * @property string $genre
 *
 */
abstract class BaseVideogenre extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'videogenre';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Videogenre|Videogenres', $n);
	}

	public static function representingColumn() {
		return 'genre';
	}

	public function rules() {
		return array(
			array('genre', 'required'),
			array('genre', 'length', 'max'=>128),
			array('intid, genre', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'intid' => Yii::t('app', 'Intid'),
			'genre' => Yii::t('app', 'Genre'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('intid', $this->intid, true);
		$criteria->compare('genre', $this->genre, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}