<?php

/**
 * This is the model base class for the table "credits".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Credits".
 *
 * Columns in table "credits" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $person
 * @property string $chanid
 * @property string $starttime
 * @property string $role
 *
 */
abstract class BaseCredits extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'credits';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Credits|Credits', $n);
	}

	public static function representingColumn() {
		return 'starttime';
	}

	public function rules() {
		return array(
			array('person', 'numerical', 'integerOnly'=>true),
			array('chanid', 'length', 'max'=>10),
			array('person, chanid, starttime, role', 'default', 'setOnEmpty' => true, 'value' => null),
			array('person, chanid, starttime, role', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'person' => Yii::t('app', 'Person'),
			'chanid' => Yii::t('app', 'Chanid'),
			'starttime' => Yii::t('app', 'Starttime'),
			'role' => Yii::t('app', 'Role'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('person', $this->person);
		$criteria->compare('chanid', $this->chanid, true);
		$criteria->compare('starttime', $this->starttime, true);
		$criteria->compare('role', $this->role, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}