<?php

/**
 * This is the model base class for the table "videocast".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Videocast".
 *
 * Columns in table "videocast" available as properties of the model,
 * and there are no model relations.
 *
 * @property string $intid
 * @property string $cast
 *
 */
abstract class BaseVideocast extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'videocast';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Videocast|Videocasts', $n);
	}

	public static function representingColumn() {
		return 'cast';
	}

	public function rules() {
		return array(
			array('cast', 'required'),
			array('cast', 'length', 'max'=>128),
			array('intid, cast', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'intid' => Yii::t('app', 'Intid'),
			'cast' => Yii::t('app', 'Cast'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('intid', $this->intid, true);
		$criteria->compare('cast', $this->cast, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}