<?php

/**
 * This is the model base class for the table "recgrouppassword".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Recgrouppassword".
 *
 * Columns in table "recgrouppassword" available as properties of the model,
 * and there are no model relations.
 *
 * @property string $recgroup
 * @property string $password
 *
 */
abstract class BaseRecgrouppassword extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'recgrouppassword';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Recgrouppassword|Recgrouppasswords', $n);
	}

	public static function representingColumn() {
		return 'password';
	}

	public function rules() {
		return array(
			array('recgroup', 'length', 'max'=>32),
			array('password', 'length', 'max'=>10),
			array('recgroup, password', 'default', 'setOnEmpty' => true, 'value' => null),
			array('recgroup, password', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'recgroup' => Yii::t('app', 'Recgroup'),
			'password' => Yii::t('app', 'Password'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('recgroup', $this->recgroup, true);
		$criteria->compare('password', $this->password, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}