<?php

/**
 * This is the model base class for the table "movies_showtimes".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "MoviesShowtimes".
 *
 * Columns in table "movies_showtimes" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property integer $theaterid
 * @property integer $movieid
 * @property string $showtimes
 *
 */
abstract class BaseMoviesShowtimes extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'movies_showtimes';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'MoviesShowtimes|MoviesShowtimes', $n);
	}

	public static function representingColumn() {
		return 'showtimes';
	}

	public function rules() {
		return array(
			array('theaterid, movieid', 'required'),
			array('theaterid, movieid', 'numerical', 'integerOnly'=>true),
			array('showtimes', 'length', 'max'=>255),
			array('showtimes', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, theaterid, movieid, showtimes', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'theaterid' => Yii::t('app', 'Theaterid'),
			'movieid' => Yii::t('app', 'Movieid'),
			'showtimes' => Yii::t('app', 'Showtimes'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('theaterid', $this->theaterid);
		$criteria->compare('movieid', $this->movieid);
		$criteria->compare('showtimes', $this->showtimes, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}