<?php

/**
 * This is the model base class for the table "settings".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Settings".
 *
 * Columns in table "settings" available as properties of the model,
 * and there are no model relations.
 *
 * @property string $value
 * @property string $data
 * @property string $hostname
 *
 */
abstract class BaseSettings extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'settings';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Settings|Settings', $n);
	}

	public static function representingColumn() {
		return 'value';
	}

	public function rules() {
		return array(
			array('value', 'length', 'max'=>128),
			array('data', 'length', 'max'=>16000),
			array('hostname', 'length', 'max'=>64),
			array('value, data, hostname', 'default', 'setOnEmpty' => true, 'value' => null),
			array('value, data, hostname', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'value' => Yii::t('app', 'Value'),
			'data' => Yii::t('app', 'Data'),
			'hostname' => Yii::t('app', 'Hostname'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('value', $this->value, true);
		$criteria->compare('data', $this->data, true);
		$criteria->compare('hostname', $this->hostname, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}