<?php

/**
 * This is the model base class for the table "iptv_channel".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "IptvChannel".
 *
 * Columns in table "iptv_channel" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $iptvid
 * @property string $chanid
 * @property string $url
 * @property string $type
 * @property string $bitrate
 *
 */
abstract class BaseIptvChannel extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'iptv_channel';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'IptvChannel|IptvChannels', $n);
	}

	public static function representingColumn() {
		return 'url';
	}

	public function rules() {
		return array(
			array('chanid, url, bitrate', 'required'),
			array('chanid, bitrate', 'length', 'max'=>10),
			array('type', 'safe'),
			array('type', 'default', 'setOnEmpty' => true, 'value' => null),
			array('iptvid, chanid, url, type, bitrate', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'iptvid' => Yii::t('app', 'Iptvid'),
			'chanid' => Yii::t('app', 'Chanid'),
			'url' => Yii::t('app', 'Url'),
			'type' => Yii::t('app', 'Type'),
			'bitrate' => Yii::t('app', 'Bitrate'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('iptvid', $this->iptvid);
		$criteria->compare('chanid', $this->chanid, true);
		$criteria->compare('url', $this->url, true);
		$criteria->compare('type', $this->type, true);
		$criteria->compare('bitrate', $this->bitrate, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}