<?php

/**
 * This is the model base class for the table "inputgroup".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Inputgroup".
 *
 * Columns in table "inputgroup" available as properties of the model,
 * and there are no model relations.
 *
 * @property string $cardinputid
 * @property string $inputgroupid
 * @property string $inputgroupname
 *
 */
abstract class BaseInputgroup extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'inputgroup';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Inputgroup|Inputgroups', $n);
	}

	public static function representingColumn() {
		return 'inputgroupname';
	}

	public function rules() {
		return array(
			array('cardinputid, inputgroupid, inputgroupname', 'required'),
			array('cardinputid, inputgroupid', 'length', 'max'=>10),
			array('inputgroupname', 'length', 'max'=>32),
			array('cardinputid, inputgroupid, inputgroupname', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'cardinputid' => Yii::t('app', 'Cardinputid'),
			'inputgroupid' => Yii::t('app', 'Inputgroupid'),
			'inputgroupname' => Yii::t('app', 'Inputgroupname'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('cardinputid', $this->cardinputid, true);
		$criteria->compare('inputgroupid', $this->inputgroupid, true);
		$criteria->compare('inputgroupname', $this->inputgroupname, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}