<?php

/**
 * This is the model base class for the table "music_directories".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "MusicDirectories".
 *
 * Columns in table "music_directories" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $directory_id
 * @property string $path
 * @property integer $parent_id
 *
 */
abstract class BaseMusicDirectories extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'music_directories';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'MusicDirectories|MusicDirectories', $n);
	}

	public static function representingColumn() {
		return 'path';
	}

	public function rules() {
		return array(
			array('path', 'required'),
			array('parent_id', 'numerical', 'integerOnly'=>true),
			array('parent_id', 'default', 'setOnEmpty' => true, 'value' => null),
			array('directory_id, path, parent_id', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'directory_id' => Yii::t('app', 'Directory'),
			'path' => Yii::t('app', 'Path'),
			'parent_id' => Yii::t('app', 'Parent'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('directory_id', $this->directory_id);
		$criteria->compare('path', $this->path, true);
		$criteria->compare('parent_id', $this->parent_id);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}