<?php

/**
 * This is the model base class for the table "recordedrating".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Recordedrating".
 *
 * Columns in table "recordedrating" available as properties of the model,
 * and there are no model relations.
 *
 * @property string $chanid
 * @property string $starttime
 * @property string $system
 * @property string $rating
 *
 */
abstract class BaseRecordedrating extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'recordedrating';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Recordedrating|Recordedratings', $n);
	}

	public static function representingColumn() {
		return 'starttime';
	}

	public function rules() {
		return array(
			array('chanid', 'length', 'max'=>10),
			array('system', 'length', 'max'=>8),
			array('rating', 'length', 'max'=>16),
			array('starttime', 'safe'),
			array('chanid, starttime, system, rating', 'default', 'setOnEmpty' => true, 'value' => null),
			array('chanid, starttime, system, rating', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'chanid' => Yii::t('app', 'Chanid'),
			'starttime' => Yii::t('app', 'Starttime'),
			'system' => Yii::t('app', 'System'),
			'rating' => Yii::t('app', 'Rating'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('chanid', $this->chanid, true);
		$criteria->compare('starttime', $this->starttime, true);
		$criteria->compare('system', $this->system, true);
		$criteria->compare('rating', $this->rating, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}