<?php

/**
 * This is the model base class for the table "customexample".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Customexample".
 *
 * Columns in table "customexample" available as properties of the model,
 * and there are no model relations.
 *
 * @property string $rulename
 * @property string $fromclause
 * @property string $whereclause
 * @property integer $search
 *
 */
abstract class BaseCustomexample extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'customexample';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Customexample|Customexamples', $n);
	}

	public static function representingColumn() {
		return 'fromclause';
	}

	public function rules() {
		return array(
			array('rulename', 'required'),
			array('search', 'numerical', 'integerOnly'=>true),
			array('rulename', 'length', 'max'=>64),
			array('fromclause, whereclause', 'length', 'max'=>10000),
			array('fromclause, whereclause, search', 'default', 'setOnEmpty' => true, 'value' => null),
			array('rulename, fromclause, whereclause, search', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'rulename' => Yii::t('app', 'Rulename'),
			'fromclause' => Yii::t('app', 'Fromclause'),
			'whereclause' => Yii::t('app', 'Whereclause'),
			'search' => Yii::t('app', 'Search'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('rulename', $this->rulename, true);
		$criteria->compare('fromclause', $this->fromclause, true);
		$criteria->compare('whereclause', $this->whereclause, true);
		$criteria->compare('search', $this->search);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}