<?php

/**
 * This is the model base class for the table "videosource".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Videosource".
 *
 * Columns in table "videosource" available as properties of the model,
 * and there are no model relations.
 *
 * @property string $sourceid
 * @property string $name
 * @property string $xmltvgrabber
 * @property string $userid
 * @property string $freqtable
 * @property string $lineupid
 * @property string $password
 * @property integer $useeit
 * @property string $configpath
 * @property integer $dvb_nit_id
 *
 */
abstract class BaseVideosource extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'videosource';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Videosource|Videosources', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array('useeit, dvb_nit_id', 'numerical', 'integerOnly'=>true),
			array('name, xmltvgrabber, userid', 'length', 'max'=>128),
			array('freqtable', 'length', 'max'=>16),
			array('lineupid, password', 'length', 'max'=>64),
			array('configpath', 'length', 'max'=>4096),
			array('name, xmltvgrabber, userid, freqtable, lineupid, password, useeit, configpath, dvb_nit_id', 'default', 'setOnEmpty' => true, 'value' => null),
			array('sourceid, name, xmltvgrabber, userid, freqtable, lineupid, password, useeit, configpath, dvb_nit_id', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'sourceid' => Yii::t('app', 'Sourceid'),
			'name' => Yii::t('app', 'Name'),
			'xmltvgrabber' => Yii::t('app', 'Xmltvgrabber'),
			'userid' => Yii::t('app', 'Userid'),
			'freqtable' => Yii::t('app', 'Freqtable'),
			'lineupid' => Yii::t('app', 'Lineupid'),
			'password' => Yii::t('app', 'Password'),
			'useeit' => Yii::t('app', 'Useeit'),
			'configpath' => Yii::t('app', 'Configpath'),
			'dvb_nit_id' => Yii::t('app', 'Dvb Nit'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('sourceid', $this->sourceid, true);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('xmltvgrabber', $this->xmltvgrabber, true);
		$criteria->compare('userid', $this->userid, true);
		$criteria->compare('freqtable', $this->freqtable, true);
		$criteria->compare('lineupid', $this->lineupid, true);
		$criteria->compare('password', $this->password, true);
		$criteria->compare('useeit', $this->useeit);
		$criteria->compare('configpath', $this->configpath, true);
		$criteria->compare('dvb_nit_id', $this->dvb_nit_id);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}