<?php

/**
 * This is the model base class for the table "streams".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Streams".
 *
 * Columns in table "streams" available as properties of the model,
 * and there are no model relations.
 *
 * @property string $folder
 * @property string $name
 * @property string $url
 * @property string $description
 * @property string $handler
 *
 */
abstract class BaseStreams extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'streams';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Streams|Streams', $n);
	}

	public static function representingColumn() {
		return 'folder';
	}

	public function rules() {
		return array(
			array('folder, name, url', 'required'),
			array('folder, name', 'length', 'max'=>100),
			array('url, description', 'length', 'max'=>255),
			array('handler', 'length', 'max'=>50),
			array('description, handler', 'default', 'setOnEmpty' => true, 'value' => null),
			array('folder, name, url, description, handler', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'folder' => Yii::t('app', 'Folder'),
			'name' => Yii::t('app', 'Name'),
			'url' => Yii::t('app', 'Url'),
			'description' => Yii::t('app', 'Description'),
			'handler' => Yii::t('app', 'Handler'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('folder', $this->folder, true);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('url', $this->url, true);
		$criteria->compare('description', $this->description, true);
		$criteria->compare('handler', $this->handler, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}