<?php

/**
 * This is the model base class for the table "videometadatagenre".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Videometadatagenre".
 *
 * Columns in table "videometadatagenre" available as properties of the model,
 * and there are no model relations.
 *
 * @property string $idvideo
 * @property string $idgenre
 *
 */
abstract class BaseVideometadatagenre extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'videometadatagenre';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Videometadatagenre|Videometadatagenres', $n);
	}

	public static function representingColumn() {
		return array(
			'idvideo',
			'idgenre',
		);
	}

	public function rules() {
		return array(
			array('idvideo, idgenre', 'required'),
			array('idvideo, idgenre', 'length', 'max'=>10),
			array('idvideo, idgenre', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'idvideo' => Yii::t('app', 'Idvideo'),
			'idgenre' => Yii::t('app', 'Idgenre'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('idvideo', $this->idvideo, true);
		$criteria->compare('idgenre', $this->idgenre, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}