<?php

/**
 * This is the model base class for the table "movies_movies".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "MoviesMovies".
 *
 * Columns in table "movies_movies" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property string $moviename
 * @property string $rating
 * @property string $runningtime
 *
 */
abstract class BaseMoviesMovies extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'movies_movies';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'MoviesMovies|MoviesMovies', $n);
	}

	public static function representingColumn() {
		return 'moviename';
	}

	public function rules() {
		return array(
			array('moviename', 'length', 'max'=>255),
			array('rating', 'length', 'max'=>10),
			array('runningtime', 'length', 'max'=>50),
			array('moviename, rating, runningtime', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, moviename, rating, runningtime', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'moviename' => Yii::t('app', 'Moviename'),
			'rating' => Yii::t('app', 'Rating'),
			'runningtime' => Yii::t('app', 'Runningtime'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('moviename', $this->moviename, true);
		$criteria->compare('rating', $this->rating, true);
		$criteria->compare('runningtime', $this->runningtime, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}