<?php

/**
 * This is the model base class for the table "keybindings".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Keybindings".
 *
 * Columns in table "keybindings" available as properties of the model,
 * and there are no model relations.
 *
 * @property string $context
 * @property string $action
 * @property string $description
 * @property string $keylist
 * @property string $hostname
 *
 */
abstract class BaseKeybindings extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'keybindings';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Keybindings|Keybindings', $n);
	}

	public static function representingColumn() {
		return 'context';
	}

	public function rules() {
		return array(
			array('context, action', 'length', 'max'=>32),
			array('description', 'length', 'max'=>255),
			array('keylist', 'length', 'max'=>128),
			array('hostname', 'length', 'max'=>64),
			array('context, action, description, keylist, hostname', 'default', 'setOnEmpty' => true, 'value' => null),
			array('context, action, description, keylist, hostname', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'context' => Yii::t('app', 'Context'),
			'action' => Yii::t('app', 'Action'),
			'description' => Yii::t('app', 'Description'),
			'keylist' => Yii::t('app', 'Keylist'),
			'hostname' => Yii::t('app', 'Hostname'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('context', $this->context, true);
		$criteria->compare('action', $this->action, true);
		$criteria->compare('description', $this->description, true);
		$criteria->compare('keylist', $this->keylist, true);
		$criteria->compare('hostname', $this->hostname, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}