<?php

/**
 * This is the model base class for the table "filemarkup".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Filemarkup".
 *
 * Columns in table "filemarkup" available as properties of the model,
 * and there are no model relations.
 *
 * @property string $filename
 * @property integer $mark
 * @property string $offset
 * @property integer $type
 *
 */
abstract class BaseFilemarkup extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'filemarkup';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Filemarkup|Filemarkups', $n);
	}

	public static function representingColumn() {
		return 'filename';
	}

	public function rules() {
		return array(
			array('filename', 'required'),
			array('mark, type', 'numerical', 'integerOnly'=>true),
			array('offset', 'length', 'max'=>20),
			array('mark, offset, type', 'default', 'setOnEmpty' => true, 'value' => null),
			array('filename, mark, offset, type', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'filename' => Yii::t('app', 'Filename'),
			'mark' => Yii::t('app', 'Mark'),
			'offset' => Yii::t('app', 'Offset'),
			'type' => Yii::t('app', 'Type'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('filename', $this->filename, true);
		$criteria->compare('mark', $this->mark);
		$criteria->compare('offset', $this->offset, true);
		$criteria->compare('type', $this->type);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}