<?php

/**
 * This is the model base class for the table "people".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "People".
 *
 * Columns in table "people" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $person
 * @property string $name
 *
 */
abstract class BasePeople extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'people';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'People|Peoples', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array('name', 'length', 'max'=>128),
			array('name', 'default', 'setOnEmpty' => true, 'value' => null),
			array('person, name', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'person' => Yii::t('app', 'Person'),
			'name' => Yii::t('app', 'Name'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('person', $this->person);
		$criteria->compare('name', $this->name, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}