<?php

/**
 * This is the model base class for the table "storagegroup".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Storagegroup".
 *
 * Columns in table "storagegroup" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property string $groupname
 * @property string $hostname
 * @property string $dirname
 *
 */
abstract class BaseStoragegroup extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'storagegroup';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Storagegroup|Storagegroups', $n);
	}

	public static function representingColumn() {
		return 'groupname';
	}

	public function rules() {
		return array(
			array('groupname', 'required'),
			array('groupname', 'length', 'max'=>32),
			array('hostname', 'length', 'max'=>64),
			array('dirname', 'length', 'max'=>235),
			array('hostname, dirname', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, groupname, hostname, dirname', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'groupname' => Yii::t('app', 'Groupname'),
			'hostname' => Yii::t('app', 'Hostname'),
			'dirname' => Yii::t('app', 'Dirname'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('groupname', $this->groupname, true);
		$criteria->compare('hostname', $this->hostname, true);
		$criteria->compare('dirname', $this->dirname, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}