<?php

/**
 * This is the model base class for the table "oldfind".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Oldfind".
 *
 * Columns in table "oldfind" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $recordid
 * @property integer $findid
 *
 */
abstract class BaseOldfind extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'oldfind';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Oldfind|Oldfinds', $n);
	}

	public static function representingColumn() {
		return array(
			'recordid',
			'findid',
		);
	}

	public function rules() {
		return array(
			array('recordid, findid', 'numerical', 'integerOnly'=>true),
			array('recordid, findid', 'default', 'setOnEmpty' => true, 'value' => null),
			array('recordid, findid', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'recordid' => Yii::t('app', 'Recordid'),
			'findid' => Yii::t('app', 'Findid'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('recordid', $this->recordid);
		$criteria->compare('findid', $this->findid);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}