<?php

/**
 * This is the model base class for the table "displayprofilegroups".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Displayprofilegroups".
 *
 * Columns in table "displayprofilegroups" available as properties of the model,
 * and there are no model relations.
 *
 * @property string $name
 * @property string $hostname
 * @property string $profilegroupid
 *
 */
abstract class BaseDisplayprofilegroups extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'displayprofilegroups';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Displayprofilegroups|Displayprofilegroups', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array('name, hostname', 'required'),
			array('name', 'length', 'max'=>128),
			array('hostname', 'length', 'max'=>64),
			array('name, hostname, profilegroupid', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'name' => Yii::t('app', 'Name'),
			'hostname' => Yii::t('app', 'Hostname'),
			'profilegroupid' => Yii::t('app', 'Profilegroupid'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('name', $this->name, true);
		$criteria->compare('hostname', $this->hostname, true);
		$criteria->compare('profilegroupid', $this->profilegroupid, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}