<?php

/**
 * This is the model base class for the table "networkiconmap".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Networkiconmap".
 *
 * Columns in table "networkiconmap" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property string $network
 * @property string $url
 *
 */
abstract class BaseNetworkiconmap extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'networkiconmap';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Networkiconmap|Networkiconmaps', $n);
	}

	public static function representingColumn() {
		return 'network';
	}

	public function rules() {
		return array(
			array('network', 'length', 'max'=>20),
			array('url', 'length', 'max'=>255),
			array('network, url', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, network, url', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'network' => Yii::t('app', 'Network'),
			'url' => Yii::t('app', 'Url'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('network', $this->network, true);
		$criteria->compare('url', $this->url, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}