<?php

/**
 * This is the model base class for the table "powerpriority".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Powerpriority".
 *
 * Columns in table "powerpriority" available as properties of the model,
 * and there are no model relations.
 *
 * @property string $priorityname
 * @property integer $recpriority
 * @property string $selectclause
 *
 */
abstract class BasePowerpriority extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'powerpriority';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Powerpriority|Powerpriorities', $n);
	}

	public static function representingColumn() {
		return 'selectclause';
	}

	public function rules() {
		return array(
			array('priorityname', 'required'),
			array('recpriority', 'numerical', 'integerOnly'=>true),
			array('priorityname', 'length', 'max'=>64),
			array('selectclause', 'length', 'max'=>16000),
			array('recpriority, selectclause', 'default', 'setOnEmpty' => true, 'value' => null),
			array('priorityname, recpriority, selectclause', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'priorityname' => Yii::t('app', 'Priorityname'),
			'recpriority' => Yii::t('app', 'Recpriority'),
			'selectclause' => Yii::t('app', 'Selectclause'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('priorityname', $this->priorityname, true);
		$criteria->compare('recpriority', $this->recpriority);
		$criteria->compare('selectclause', $this->selectclause, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}