<?php

/**
 * This is the model base class for the table "callsignnetworkmap".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Callsignnetworkmap".
 *
 * Columns in table "callsignnetworkmap" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property string $callsign
 * @property string $network
 *
 */
abstract class BaseCallsignnetworkmap extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'callsignnetworkmap';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Callsignnetworkmap|Callsignnetworkmaps', $n);
	}

	public static function representingColumn() {
		return 'callsign';
	}

	public function rules() {
		return array(
			array('callsign, network', 'length', 'max'=>20),
			array('callsign, network', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, callsign, network', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'callsign' => Yii::t('app', 'Callsign'),
			'network' => Yii::t('app', 'Network'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('callsign', $this->callsign, true);
		$criteria->compare('network', $this->network, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}