<?php

/**
 * This is the model base class for the table "pidcache".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Pidcache".
 *
 * Columns in table "pidcache" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $chanid
 * @property integer $pid
 * @property integer $tableid
 *
 */
abstract class BasePidcache extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'pidcache';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Pidcache|Pidcaches', $n);
	}

	public static function representingColumn() {
		return 'chanid';
	}

	public function rules() {
		return array(
			array('chanid, pid, tableid', 'numerical', 'integerOnly'=>true),
			array('chanid, pid, tableid', 'default', 'setOnEmpty' => true, 'value' => null),
			array('chanid, pid, tableid', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'chanid' => Yii::t('app', 'Chanid'),
			'pid' => Yii::t('app', 'Pid'),
			'tableid' => Yii::t('app', 'Tableid'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('chanid', $this->chanid);
		$criteria->compare('pid', $this->pid);
		$criteria->compare('tableid', $this->tableid);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}