<?php

/**
 * This is the model base class for the table "gameplayers".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Gameplayers".
 *
 * Columns in table "gameplayers" available as properties of the model,
 * and there are no model relations.
 *
 * @property string $gameplayerid
 * @property string $playername
 * @property string $workingpath
 * @property string $rompath
 * @property string $screenshots
 * @property string $commandline
 * @property string $gametype
 * @property string $extensions
 * @property integer $spandisks
 *
 */
abstract class BaseGameplayers extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'gameplayers';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Gameplayers|Gameplayers', $n);
	}

	public static function representingColumn() {
		return 'playername';
	}

	public function rules() {
		return array(
			array('commandline', 'required'),
			array('spandisks', 'numerical', 'integerOnly'=>true),
			array('playername, gametype', 'length', 'max'=>64),
			array('workingpath, rompath, screenshots', 'length', 'max'=>255),
			array('extensions', 'length', 'max'=>128),
			array('playername, workingpath, rompath, screenshots, gametype, extensions, spandisks', 'default', 'setOnEmpty' => true, 'value' => null),
			array('gameplayerid, playername, workingpath, rompath, screenshots, commandline, gametype, extensions, spandisks', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'gameplayerid' => Yii::t('app', 'Gameplayerid'),
			'playername' => Yii::t('app', 'Playername'),
			'workingpath' => Yii::t('app', 'Workingpath'),
			'rompath' => Yii::t('app', 'Rompath'),
			'screenshots' => Yii::t('app', 'Screenshots'),
			'commandline' => Yii::t('app', 'Commandline'),
			'gametype' => Yii::t('app', 'Gametype'),
			'extensions' => Yii::t('app', 'Extensions'),
			'spandisks' => Yii::t('app', 'Spandisks'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('gameplayerid', $this->gameplayerid, true);
		$criteria->compare('playername', $this->playername, true);
		$criteria->compare('workingpath', $this->workingpath, true);
		$criteria->compare('rompath', $this->rompath, true);
		$criteria->compare('screenshots', $this->screenshots, true);
		$criteria->compare('commandline', $this->commandline, true);
		$criteria->compare('gametype', $this->gametype, true);
		$criteria->compare('extensions', $this->extensions, true);
		$criteria->compare('spandisks', $this->spandisks);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}