<?php

/**
 * This is the model base class for the table "channelgroupnames".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Channelgroupnames".
 *
 * Columns in table "channelgroupnames" available as properties of the model,
 * and there are no model relations.
 *
 * @property string $grpid
 * @property string $name
 *
 */
abstract class BaseChannelgroupnames extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'channelgroupnames';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Channelgroupnames|Channelgroupnames', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array('name', 'length', 'max'=>64),
			array('name', 'default', 'setOnEmpty' => true, 'value' => null),
			array('grpid, name', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'grpid' => Yii::t('app', 'Grpid'),
			'name' => Yii::t('app', 'Name'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('grpid', $this->grpid, true);
		$criteria->compare('name', $this->name, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}