<?php

/**
 * This is the model base class for the table "jumppoints".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Jumppoints".
 *
 * Columns in table "jumppoints" available as properties of the model,
 * and there are no model relations.
 *
 * @property string $destination
 * @property string $description
 * @property string $keylist
 * @property string $hostname
 *
 */
abstract class BaseJumppoints extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'jumppoints';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Jumppoints|Jumppoints', $n);
	}

	public static function representingColumn() {
		return 'destination';
	}

	public function rules() {
		return array(
			array('destination, keylist', 'length', 'max'=>128),
			array('description', 'length', 'max'=>255),
			array('hostname', 'length', 'max'=>64),
			array('destination, description, keylist, hostname', 'default', 'setOnEmpty' => true, 'value' => null),
			array('destination, description, keylist, hostname', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'destination' => Yii::t('app', 'Destination'),
			'description' => Yii::t('app', 'Description'),
			'keylist' => Yii::t('app', 'Keylist'),
			'hostname' => Yii::t('app', 'Hostname'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('destination', $this->destination, true);
		$criteria->compare('description', $this->description, true);
		$criteria->compare('keylist', $this->keylist, true);
		$criteria->compare('hostname', $this->hostname, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}