<?php

/**
 * This is the model base class for the table "schemalock".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Schemalock".
 *
 * Columns in table "schemalock" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $schemalock
 *
 */
abstract class BaseSchemalock extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'schemalock';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Schemalock|Schemalocks', $n);
	}

	public static function representingColumn() {
		return 'schemalock';
	}

	public function rules() {
		return array(
			array('schemalock', 'numerical', 'integerOnly'=>true),
			array('schemalock', 'default', 'setOnEmpty' => true, 'value' => null),
			array('schemalock', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'schemalock' => Yii::t('app', 'Schemalock'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('schemalock', $this->schemalock);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}