<?php

/**
 * This is the model base class for the table "music_genres".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "MusicGenres".
 *
 * Columns in table "music_genres" available as properties of the model,
 * and there are no model relations.
 *
 * @property string $genre_id
 * @property string $genre
 *
 */
abstract class BaseMusicGenres extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'music_genres';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'MusicGenres|MusicGenres', $n);
	}

	public static function representingColumn() {
		return 'genre';
	}

	public function rules() {
		return array(
			array('genre', 'length', 'max'=>255),
			array('genre', 'default', 'setOnEmpty' => true, 'value' => null),
			array('genre_id, genre', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'genre_id' => Yii::t('app', 'Genre'),
			'genre' => Yii::t('app', 'Genre'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('genre_id', $this->genre_id, true);
		$criteria->compare('genre', $this->genre, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}