<?php

/**
 * This is the model base class for the table "websites".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Websites".
 *
 * Columns in table "websites" available as properties of the model,
 * and there are no model relations.
 *
 * @property string $id
 * @property string $category
 * @property string $name
 * @property string $url
 *
 */
abstract class BaseWebsites extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'websites';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Websites|Websites', $n);
	}

	public static function representingColumn() {
		return 'category';
	}

	public function rules() {
		return array(
			array('category, name, url', 'required'),
			array('category, name', 'length', 'max'=>100),
			array('url', 'length', 'max'=>255),
			array('id, category, name, url', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'category' => Yii::t('app', 'Category'),
			'name' => Yii::t('app', 'Name'),
			'url' => Yii::t('app', 'Url'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('category', $this->category, true);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('url', $this->url, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}