<?php

/**
 * This is the model base class for the table "videopart".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Videopart".
 *
 * Columns in table "videopart" available as properties of the model,
 * and there are no model relations.
 *
 * @property string $fileid
 * @property string $videoid
 * @property integer $order
 *
 */
abstract class BaseVideopart extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'videopart';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Videopart|Videoparts', $n);
	}

	public static function representingColumn() {
		return array(
			'videoid',
			'order',
		);
	}

	public function rules() {
		return array(
			array('fileid, videoid', 'required'),
			array('order', 'numerical', 'integerOnly'=>true),
			array('fileid', 'length', 'max'=>20),
			array('videoid', 'length', 'max'=>10),
			array('order', 'default', 'setOnEmpty' => true, 'value' => null),
			array('fileid, videoid, order', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'fileid' => Yii::t('app', 'Fileid'),
			'videoid' => Yii::t('app', 'Videoid'),
			'order' => Yii::t('app', 'Order'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('fileid', $this->fileid, true);
		$criteria->compare('videoid', $this->videoid, true);
		$criteria->compare('order', $this->order);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}