<?php

/**
 * This is the model base class for the table "music_smartplaylist_categories".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "MusicSmartplaylistCategories".
 *
 * Columns in table "music_smartplaylist_categories" available as properties of the model,
 * and there are no model relations.
 *
 * @property string $categoryid
 * @property string $name
 *
 */
abstract class BaseMusicSmartplaylistCategories extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'music_smartplaylist_categories';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'MusicSmartplaylistCategories|MusicSmartplaylistCategories', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array('name', 'required'),
			array('name', 'length', 'max'=>128),
			array('categoryid, name', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'categoryid' => Yii::t('app', 'Categoryid'),
			'name' => Yii::t('app', 'Name'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('categoryid', $this->categoryid, true);
		$criteria->compare('name', $this->name, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}