<?php

/**
 * This is the model base class for the table "mcc_record_templates".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "RecordTemplates".
 *
 * Columns in table "mcc_record_templates" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property string $name
 * @property integer $record_id
 * @property integer $type
 * @property string $description
 *
 */
abstract class BaseRecordTemplates extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'mcc_record_templates';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'RecordTemplates|RecordTemplates', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array('name, record_id, type', 'required'),
			array('record_id, type', 'numerical', 'integerOnly'=>true),
			array('name, description', 'length', 'max'=>255),
			array('description', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, name, record_id, type, description', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'name' => Yii::t('app', 'Name'),
			'record_id' => Yii::t('app', 'Record'),
			'type' => Yii::t('app', 'Type'),
			'description' => Yii::t('app', 'Description'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('record_id', $this->record_id);
		$criteria->compare('type', $this->type);
		$criteria->compare('description', $this->description, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}