<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Access denied.' => 'Zugriff verweigert',
  'Add' => 'Hinzufügen',
  'Add child' => 'Kindelement hinzufügen',
  'Add {type}' => '{type} hinzufügen',
  'Ancestors' => 'Vorgängerelemente',
  'Are you sure you want to delete this item?' => 'Sind Sie sicher, daß dieses Element gelöscht werden soll?',
  'Assign' => 'Zuweisen',
  'Assign permission' => 'Berechtigung zuweisen',
  'Assigned items' => 'Zugewiesene Elemente',
  'Assignments' => 'Zuweisungen',
  'Business rule' => 'Geschäftslogik',
  'Cancel' => 'Abbrechen',
  'Create' => 'Erstellen',
  'Data' => 'Daten',
  'Delete' => 'Löschen',
  'Descendants' => 'Nachfolgeelemente',
  'Description' => 'Beschreibung',
  'Edit' => 'Bearbeiten',
  'Invalid request.' => 'Ungültige Anfrage.',
  'Item does not exist.' => 'Das Element existiert nciht.',
  'Items' => 'Elemente',
  'Items assigned to this user' => 'Dem Benutzer zugewiesene Elemente',
  'New {type}' => 'Neuer {type}',
  'No assignments found.' => 'Keine Zuweisungen gefunden.',
  'No {type} found.' => 'Kein {type} gefunden',
  'Page not found.' => 'Seite nicht gefunden.',
  'Permissions' => 'Berechtigungen',
  'Permissions granted by this item' => 'Berechtigungen durch dieses Element',
  'Permissions that inherit this item' => 'Berechtigungen welche dieses Element vererben',
  'Remove' => 'Entfernen',
  'Revoke' => 'Entziehen',
  'Save' => 'Speichern',
  'Select item' => 'Element wählen',
  'System name' => 'Systemname',
  'System name cannot be changed after creation.' => 'der Systemname kann nach Erstellung nicht mehr geändert werden.',
  'This item does not have any ancestors.' => 'Dieses Element hat keine Vorgängerelemente.',
  'This item does not have any descendants.' => 'Dieses Element hat keine Kindelemente.',
  'This user does not have any assignments.' => 'Dieses Element hat keine Zuweisungen.',
  'Type' => 'Typ',
  'User' => 'Benutzer',
  'View' => 'Ansehen',
  'operation|operations' => 'Operation|Operationen',
  'role|roles' => 'Rolle|Rollen',
  'task|tasks' => 'Aufgaben',
);
