<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Can\'t write configuration file \'{filename}\'. Please run \'extras/fixPermissions.sh\' to correct file permissions.' => 'Die Konfigurationsdatei \'{filename}\' konnte nicht geschrieben werden. Bitte führen Sie das Skript \'extras/fixPermissions.sh\' aus um die Dateiberechtigungen zu korrigieren.',
  'Config item \'{key}\' generated an error: \'{message}\'' => 'Der Konfigurationseintrag \'{key}\' erzeugte einen Fehler: \'{message}\'',
  'Default value' => 'Vorgabewert',
  'Green means that you have set this config item.' => 'Grün bedeutet, daß dieser Konfigurationseintrag manuell gesetzt wurde.',
  'No test defined.' => 'Kein Test definiert.',
  'Red means that you have not set this config item, but the item is required for the application to work properly.' => 'Rot bedeutet, daß dieser Konfigurationseintrag manuell gesetzt werden muß. Er ist für die Applikation zwingend erforderlich und es kann kein sinnvoller Wert vorgegeben werden.',
  'Save' => 'Speichern',
  'Test failed:' => 'Test fehlgeschlagen:',
  'Test passed.' => 'Test erfolgreich.',
  'The config items below show you if your application is set up properly:' => 'Die folgenden Konfigurationseinträge zeigen ob die Applikation korrekt konfiguriert ist:',
  'This config item must be set to a custom value!' => 'Dieser Konfigurationseintrag muß manuell gesetzt werden!',
  'Yellow means that you have not set this config item and the default value is used.' => 'Gelb bedeutet, daß dieser Konfigurationseintrag nicht manuell gesetzt wurde und der Vorgabewert benutzt wird.',
);
